[package]
name = "neon-sharing-binary-data-example"
version = "0.1.0"
build = "build.rs"

[lib]
name = "neon_sharing_binary_data_example"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.3.1"

[dependencies]
neon = "0.3.1"
cslice = "0.3.0"
