[package]
name = "event-emitter"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[lib]
name = "event_emitter_example"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.1"

[dependencies]
neon = "0.3.1"
