[package]
name = "neon-fibonacci-async-task"
version = "0.1.0"
build = "build.rs"

[lib]
name = "neon_fibonacci_async_task"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.1"

[dependencies]
neon = "0.3.1"
num-bigint = "0.2"
num-traits = "0.2"
