[package]
name = "neon-fibonacci-task"
version = "0.1.0"
build = "build.rs"

[lib]
name = "neon_fibonacci_task"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2"

[dependencies]
neon = "0.2"
num-bigint = "0.2"
num-traits = "0.2"
