[package]
name = "thread-count"
version = "0.1.0"
build = "build.rs"

[lib]
name = "thread_count"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2"

[dependencies]
neon = "0.2"
num_cpus = "1.4.0"
